
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public int UserID { get; set; }

    public string EmployeeID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public Nullable<int> ProjectID { get; set; }

    public Nullable<int> TaskID { get; set; }



    public virtual Project Project { get; set; }

    public virtual Task Task { get; set; }

}

}
